### ISSUE TITLE
"Not found" upon logging in on Android 33

### ISSUE THREAD

**Issue by MilesAdamson** [auth0/auth0-flutter#321] opened 2023-10-19 18:49 UTC
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Upon logging in with `webAuthentication` and `login`, after entering my username and password, I see a screen which just says "not found". The future does not complete from login and I do not get the login tokens. Pressing X from this screen counts as cancelling the login.

![image](https://github.com/auth0/auth0-flutter/assets/29047682/6ef2dc7c-c53e-46f6-8438-55813dcf96d3)

### Reproduction

1. Clone sample project and follow readme https://github.com/auth0-samples/auth0-flutter-samples/blob/main/sample/README.md
2. Update auth0 secrets and change android applicationId
3. Build and run app
4. Login successfully

### Additional context

The same thing happens with my actual app, but I can reproduce it in the sample project as well.

### auth0_flutter version

1.2.0

### Flutter version

3.10.6

### Platform

Android

### Platform version(s)

Android 33

**Comment by MilesAdamson** [comment] 2023-10-19 19:06
I tried it also on Android 12, SDK version 29 and the same thing is happening. Maybe it has something do do with my existing auth0 setup?

Previously, login was happening with a POST to `/oauth/token` and everything else was handled on our end. Now, I am trying to change this to allowing single sign on

**Comment by MilesAdamson** [comment] 2023-10-19 21:54
This appears to be an Android issue, it's working fine on my iOS device with the same code. Both the same project and my own are working fine and I get tokens back

**Comment by jdmanifest** [comment] 2023-10-20 02:25
I'm having the same problem, will report back if I find a solution.

**Comment by jdmanifest** [comment] 2023-10-20 03:22
So if you're defining https as a custom scheme, that seems to have been my problem.

**Comment by Widcket** [comment] 2023-10-20 08:05
Closing, as the issue seems to have been resolved. Please feel free to ping if you'd prefer to reopen.

**Closed by Widcket** 2023-10-20 08:05 UTC
Labels: android

**Comment by MilesAdamson** [comment] 2023-10-20 15:30
@Widcket could you direct me to any solutions/docs on how people fixed this in the past please? The sample project has this issue out of the box for me so I'm not sure how this is resolved

**Comment by Widcket** [comment] 2023-10-20 15:54
@poovamraj could you please take this one?

**Comment by MilesAdamson** [comment] 2023-10-20 18:36
Please re-open this issue, as it seems to be common and unresolved. 

I tried changing the scheme to "demo" and adding another callback url in Auth0, but that didn't work. However it did behave differently - after logging in, I was taken back to the app, but the `future` never completed and I couldn't get the login result out of it. I have a breakpoint after the login call, and neither the next line nor the one inside the `catch(e)` ever get hit. Line 95 of `web_authentication` from the plugin also never gets hit, which is the one after logging in:

 `await _credentialsManager?.storeCredentials(credentials);`

https://community.auth0.com/t/i-am-using-default-schema-for-flutter-webauthentication-login-but-after-login-i-am-not-coming-back-in-app/118873

https://stackoverflow.com/questions/76031825/auth0-integration-in-flutter-android-not-returning-to-app-after-login-logout

https://community.auth0.com/t/flutter-webauth-redirects-to-not-found-page/89557

https://community.auth0.com/t/flutter-gives-not-found-instead-of-redirecting-to-app/98929

https://github.com/auth0/auth0-flutter/issues/291

**Comment by jdmanifest** [comment] 2023-10-21 09:18
> Please re-open this issue, as it seems to be common and unresolved. I tried changing the scheme to "demo" and adding another callback url in Auth0, but that didn't work. However it did behave differently - I just get a blank webpage and cannot log in.
> 
> https://community.auth0.com/t/i-am-using-default-schema-for-flutter-webauthentication-login-but-after-login-i-am-not-coming-back-in-app/118873
> 
> https://stackoverflow.com/questions/76031825/auth0-integration-in-flutter-android-not-returning-to-app-after-login-logout
> 
> https://community.auth0.com/t/flutter-webauth-redirects-to-not-found-page/89557
> 
> https://community.auth0.com/t/flutter-gives-not-found-instead-of-redirecting-to-app/98929
> 
> #291

Can you post you're callback links from ur auth0 application off the dashboard? Sounds like you may have them in their wrong.

**Comment by ajyong** [comment] 2023-10-23 22:18
I'm not sure the root cause for custom schemes but for `https`, the Flutter documentation is lacking an important step: supporting Android App Links.

This guidance is provided [here](https://auth0.com/blog/get-started-with-flutter-authentication/#Configure-the-SDK) and [here](https://auth0.com/docs/quickstart/native/flutter/interactive#configure-android) and is missing from the [Pub.dev](https://pub.dev/packages/auth0_flutter#configure-auth0) equivalent.  Although it's covered in `EXAMPLES.md`, I thought it be better if it was also surfaced in the main README.  I've submitted #324 to do that.
